server:
  port: 8761  #eureka默认端口号8761

spring:
  application:
    name: eureka-server #给当前eureka服务命名

eureka:
  instance: #eureka实例
    hostname: eurekaserver1 #eureka实例的主机名字
  client:
    register-with-eureka: false #表示是否将自己注册到eureka server 默认为true
    fetch-registry: false   #表示是否从eureka server获取注册信息 默认为true
    service-url:    #eureka server的地址
      defaultZone:  http://seq:123@${eureka.instance.hostname}:${server.port}/eureka/
      
security:
  basic:
    enabled: true   #eureka启用安全认证
  user:
    name: seq
    password: 123
    